"""Ports for the ChatStore boundary."""

from collections.abc import Iterator
from typing import Any, Protocol

from src.domain.chatstore.dtos import (
    AppendChatMessageRequest,
    ChatRecord,
    CreateChatRequest,
)
from src.domain.models import Chat


class ChatStore(Protocol):
    def create_chat(self, req: CreateChatRequest) -> ChatRecord: ...
    def get_chat(self, chat_slug: str) -> ChatRecord | None: ...
    def list_chats(self) -> list[ChatRecord]: ...
    def rename_chat(self, chat_slug: str, title: str) -> ChatRecord: ...
    def delete_chat(self, chat_slug: str) -> None: ...
    def append_message(self, req: AppendChatMessageRequest) -> ChatRecord: ...
    def mark_promoted(self, chat_slug: str, work_slug: str) -> ChatRecord: ...
    def set_chat_session_id(self, chat_slug: str, session_id: str) -> None: ...
    def set_chat_option(self, chat_slug: str, key: str, value: Any) -> None: ...
    def touch_chat(self, chat_slug: str) -> None: ...
    def claim_initial_prompt(self, chat_slug: str) -> str | None: ...
    def append_transcript_event_with_seq(
        self, chat_slug: str, payload: dict[str, Any]
    ) -> int: ...
    def read_transcript_from_cursor(
        self, chat_slug: str, cursor: int
    ) -> Iterator[dict[str, Any]]: ...
    def write_chat_compaction_doc(
        self, chat_slug: str, filename: str, content: str
    ) -> str: ...
    def read_chat_compaction_doc(
        self, chat_slug: str, filename: str
    ) -> tuple[str, str] | None: ...


class ChatRepository(Protocol):
    def add_chat(self, chat: Chat) -> Chat: ...
    def update_chat(self, chat: Chat) -> Chat: ...
    def get_chat_by_slug(self, slug: str) -> Chat | None: ...
    def list_chats(self) -> list[Chat]: ...
    def delete_chat(self, slug: str) -> None: ...


class ChatFiles(Protocol):
    def ensure_chat_dir(self, chat_slug: str) -> None: ...
    def remove_chat_dir(self, chat_slug: str) -> None: ...
    def write_chat_json(self, chat_slug: str, data: dict[str, object]) -> None: ...
    def read_chat_json(self, chat_slug: str) -> dict[str, object] | None: ...
    def append_transcript_event(self, chat_slug: str, event: dict[str, Any]) -> None: ...
    def last_seq(self, chat_slug: str) -> int: ...
    def read_transcript(self, chat_slug: str) -> Iterator[dict[str, Any]]: ...
    def write_chat_compaction_doc(
        self, chat_slug: str, filename: str, content: str
    ) -> str: ...
    def read_chat_compaction_doc(
        self, chat_slug: str, filename: str
    ) -> tuple[str, str] | None: ...


__all__ = ["ChatFiles", "ChatRepository", "ChatStore"]
