"""Agent boundary: AgentAdapter port, AgentConfig hierarchy, AgentEvent union."""

from src.domain.agents.context_render import render_agent_contexts
from src.domain.agents.configs import (
    AMP_DEFAULT_AUTO_ALLOWED_TOOLS,
    AgentConfig,
    AmpAgentConfig,
    AmpMode,
    AmpPermissionMode,
    ClaudeAgentConfig,
    ClaudeEffort,
    ClaudeModel,
    ClaudePermissionMode,
    CommonAgentConfig,
)
from src.domain.agents.events import (
    AgentEvent,
    ArtifactMarker,
    Error,
    MessageComplete,
    MessageDelta,
    PermissionDecision,
    PermissionDecisionValue,
    PermissionRequest,
    SessionEstablished,
    StatusChange,
    ThinkingComplete,
    ThinkingDelta,
    ToolCall,
    ToolResult,
    TurnMetrics,
)
from src.domain.agents.ports import AgentAdapter, AgentStartContext
from src.domain.agents.specs import (
    SPECS,
    AmpSpec,
    ClaudeSpec,
    EnumOption,
    ProviderDescriptor,
    Spec,
    TextOption,
)
from src.domain.agents.system_prompt import render_system_prompt

__all__ = [
    "AMP_DEFAULT_AUTO_ALLOWED_TOOLS",
    "SPECS",
    "AgentAdapter",
    "AgentConfig",
    "AgentEvent",
    "AgentStartContext",
    "AmpAgentConfig",
    "AmpMode",
    "AmpPermissionMode",
    "AmpSpec",
    "ArtifactMarker",
    "ClaudeAgentConfig",
    "ClaudeEffort",
    "ClaudeModel",
    "ClaudePermissionMode",
    "ClaudeSpec",
    "CommonAgentConfig",
    "EnumOption",
    "Error",
    "MessageComplete",
    "MessageDelta",
    "PermissionDecision",
    "PermissionDecisionValue",
    "PermissionRequest",
    "ProviderDescriptor",
    "SessionEstablished",
    "Spec",
    "StatusChange",
    "TextOption",
    "ThinkingComplete",
    "ThinkingDelta",
    "ToolCall",
    "ToolResult",
    "TurnMetrics",
    "render_agent_contexts",
    "render_system_prompt",
]
